# See http://readme.drone.io/0.5/usage/overview

# See https://git.osgeo.org/gogs/geos/geos-docker
test-image: &test-image docker.kbt.io/geos/build-test:alpine

pipeline:
  clone:
    image: plugins/git
    depth: 50
    recursive: false
  build:
    image: *test-image
    commands:
      - ./autogen.sh
      - CXXFLAGS="-O0" ./configure
      - make
  check:
    image: *test-image
    commands:
      - CXXFLAGS="-O0" make check
